n7space/asn1scc.IDE

- asn1acn.cpp
- asn1acn.mimetypes.xml
- asn1acn.pro
- asn1acn.qrc
- asndocument.cpp
- asndocument.h
- asneditor.cpp
- asneditor.h
* "Open with" have now "ASN.1 Editor" option for ".asn" and ".asn1" files
* In asn files "toggle comment (Ctrl+/)" works (and only that)
seems like a good starting point.
AsnDocument will probably be the thing shared between editor/outline/etc.
I'm not entirely happy with file names etc., but I tried to follow existing code conventions from QtCreator.
> ASNIDE-7 - AsnEditor added

- asn1acn.pro
- asnautocompleter.cpp
- asnautocompleter.h
- asncompletionassist.cpp
- asncompletionassist.h
- asneditor.cpp
So we have both: autocompleting "()" and completion - assist, with fixed suggestions (yet).
I'm not sure, should I add "code model" in this task or does separate one is needed (this is potential place for integration with asn1scc).
> Asnide 15 autocomplete placeholder

- asn1acn.cpp
- asn1acnconstants.h
- asneditor.cpp
- asneditor.h
'Jump to' action will be triggered in following cases: when 'CTRL + left click' will be used on any item, or after selecting 'Follow Symbol Under Cursor', which will work after choosing it from context menu shown after right click, or pressing F2 button. 
Moving the cursor over any word while pressing Ctrl button, will cause the whole word to be underlined. Triggering 'jump to' will move cursor to the first occurrence of the word in active file. Let assume that there is following test file used: 
1: Test      File
2: Test      File
3: Test      File
4: Test      File
5: Test      File
6: F
7: e
Triggering 'jump to' on any of the word 'Test' will move cursor to 'Test' in line 1. Triggering the action on letter 'F' will move cursor to word 'File' in line 1.  Triggering the action on letter …
> ASNIDE-13 Added 'jump to' placeholder with simple jumping capability

- asn1acn.cpp
- asn1acn.pro
- asnparseddocument.h
- asnstructuresview.cpp
- asnstructuresview.h
There is full file path shown as the widget body. It is responsive to change in currently open document (which should not be, as the widget shall be rather connected with contents of the documents, but this way the widget looks 'alive'). The widget have much in common with Outline widget, but IMO it is better to create base class for both the widgets later.
> Asnide 12 create structures project tree view placeholder

- asn1acn.cpp
- asn1acn.pro
- asndocument.cpp
- asndocumentprocessor.cpp
- asndocumentprocessor.h
- asneditor.cpp
- asnoutline.cpp
- asnoutline.h
- asnoverviewmodel.cpp
- asnoverviewmodel.h
- asnparseddatastorage.cpp
- asnparseddatastorage.h
- asnparseddocument.cpp
- asnparseddocument.h
- asnparsedobject.cpp
- asnparsedobject.h
- asnstructuresview.cpp
- asnstructuresview.h
- projectwatcher.cpp
- projectwatcher.h
List of changes included in this review: 
- tree model used now is capable of storing actual trees (before it was more of a list). New class AsnParsedObject was created to help handle it. 
- the model was used in both outline widget and Structure View widget
- the example usage of AstXmlParser was included. 
- ProjectWatcher class was created, so documents are now parsed after opening project or modifying files list in project instead of performing parsing after document was opened in editor. 
Future improvements:
- There can't be more than one instance of StructuresView widget. This is because every instance creates its own root node with AsnParsedFile object instances as children. Since those are stored globally and can not have multiple parents, attemt to create second structures view …
> Asnide 19 connect asn.1 editor with project tree view

- asn1acn.cpp
- asn1acn.pro
- asn1acnconstants.h
- asn1acnjsextension.cpp
- asn1acnjsextension.h
- templates/wizards/files/acn/template.acn
- templates/wizards/files/acn/wizard.json
- templates/wizards/files/asn1/template.asn
- templates/wizards/files/asn1/wizard.json
Support for Acn / Asn data models was added. User will be able to choose if new Asn file should have .asn or .asn1 extension. Contents of newly created files is to be agreed.
> ASNIDE-39 - Added ASN.1/ACN support for new file wizard

- acneditor.cpp
- asn1acn.pro
- asneditor.cpp
- asnsnippetprovider.cpp
- autocompleter.cpp
- autocompleter.h
now [] () {} are autocompleted in ACN files
> ASNIDE-23 AutoCompleter connected to AcnEditor

- projectcontenthandler.cpp
- projectcontenthandler.h
In fact, after renaming a file project does not need to be rebuilt,  because it does not change contents of any file. Propsed solution does that anyway, to avoid exposing internal parts of model nodes and parsed documents. It is justified in my opinion, as renaming the file in IDE is rather rare event.
> ASNIDE-122 Fixed handling of file renaming

- asn1acn.pro
- templates/wizards/projects/asn1acn/createSources.pri
- templates/wizards/projects/asn1acn/createSourcesList.pri
- templates/wizards/projects/asn1acn/file.pro
- templates/wizards/projects/asn1acn/handleAsn1AcnBuild.pri
- templates/wizards/projects/asn1acn/wizard.json
The solution implemented uses the approach to create list of sources to be built prior to actual build. This approach turned out to be working. It has go some flaws, and some solutions could be discussed. Firstly, I decided to give up on from using QMAKE_EXTRA_COMPILERS construct. This is because it does not really match the needs of project. Using QMAKE_EXTRA_COMPILERS assumes, two scenarios: the one in which one input file is converted into other file (like tranforming .cpp files into .o files), and the other, in which set of files is combined into one result file (like combining .o files into runnable binary). Our case is neither of those, as we are using multiple input files to combine them into multiple output files, but without strict matching input files and output files, so using …
> Asnide 125 qmake project asn1scc support

- asn1acn.cpp
- asn1acn.pro
- outline.cpp
- overviewindexupdater.cpp
- overviewindexupdater.h
- overviewwidget.cpp
- overviewwidget.h
- structuresview.cpp
- structuresview.h
- structuresviewindexupdater.cpp
- structuresviewindexupdater.h
- tests/overviewindexupdater_tests.cpp
- tests/overviewindexupdater_tests.h
- tests/structuresviewindexupdater_tests.cpp
- tests/structuresviewindexupdater_tests.h
The test were created alongside with the feature. There are tests for both classes introduced. One of the class inherits from the other, extending it a little. I had some doubts while creating tests, among which was: if there should be one or two test classes. I've decided that two are better in terms it clearly shows what is tested in which class. A lot of code in both test classes is similar, so it was natural temptation to store it in one base class (which would mimic the structure of classes being tested), but I rejected the idea, as this would make test code as complex as classes tested. Another thing was to decide if tests of StructuresViewIndexUpdater should cover all cases, including the ones being covered by the base class tests - I decided no, and made it test only the funciton …
> Asnide 137 highlighting item under cursor with tests

- .travis.yml
It's a temporary solution because our builds have to wait for a very
long time to get available OSX machine.
Better solution requires changes on Travis side - either more OSX
machines or possibility to skip osx builds and run them only from cron
(for example).
-------------------------
mail about passing is sent when all "required" jobs finish, so probably no mail is sent when "allowed failures" fails. So they will require some manual inspection from time to time (probably on master only)
If @psockoN7 you're ok with that - plz accept :)
> Travis will allow failures on OSX

- documentsource.cpp
- documentsource.h
- projectwatcher.cpp
- projectwatcher.h
- tests/documentprocessorstub.cpp
- tests/documentprocessorstub.h
The issue was caused by the fact, that in case all the "files" were removed during test, the status of processing was not changed. 
I have also discovered that license in some file was invalid, so changed it to proper one.
> Asnide 162 fix soft assert reported during unit tests

- structuresview.cpp
- tests/structuresviewindexupdater_tests.cpp
I've noticed that Clang build was failing, and this is the fix.
> Fixed clang build error and warning

- completion/autocompleter.cpp
- completion/autocompleter.h
- tests/autocompleter_tests.cpp
- tests/autocompleter_tests.h
Changes introduced: 
- Handled comment inside quotes (comment inside quotes will not be treated as comment any more)
- Changed adding double quotes logic to make more sense
- Handled situation in which BEGIN / END keyword is in either commented or in string
- Added more tests
> Asnide 165 asnide 167 autocompletion fixes

- tree-views/typestreewidget.cpp
- tree-views/typestreewidget.h
I've analised if the widget could be created in similar way as outline widget, which could be beneficial, because outline has support for cursor synchronization created already. Outline is connected with editor being changed and when editor == null, than the widget is destroyed. Such behaviour is not wanted in terms of Types View, because the widget needs to be present even when editor is closed. Since that I've decided that it is better to add support in relevant place manually.
> ASNIDE-169 Added text cursor synchronization toggle button

- editor.cpp
- editor.h
- tree-views/indexupdater.cpp
- tree-views/indexupdater.h
- tree-views/typestreeindexupdater.cpp
- tree-views/typestreeindexupdater.h
There were two different crashes while working with splitted editor.  One was common "read after free" issue. The other one came from connecting signal to lambda expression. Similar construction is still used, which should be kept for further dicussion.
> ASNIDE-175 Fixed crashes when working with splitted text editor

- asn1acn.pro
- src/asn1acn.cpp
- src/asneditor.cpp
- src/linkcreator.cpp
- src/linkcreator.h
- src/tests/linkcreator_tests.cpp
- src/tests/linkcreator_tests.h
Fixed crash (nullptr dereference), and added tests to prove crash does not occur any more.
> Asnide 220 fix crash when creating link

- src/astxmlparser.cpp
- src/astxmlparser.h
- src/tests/astxmlparser_tests.cpp
- src/tests/astxmlparser_tests.h
The only practical difference between CHOICE and SEQUENCE in AST is in data provided by children:
Choice contains `EnumID` field
`<ChoiceChild VarName="choiceChild-1" Line="12" CharPositionInLine="4" EnumID ="choiceChild_1_PRESENT">`
while sequence contains `Optional` field
`<SequenceOrSetChild VarName="nestetSequenceChild-2" Optional="False" Line="30" CharPositionInLine="8">`
> ASNIDE-209 Implemented choice children parsing. Added related unit test.

- schemas/asn1-lib-module-schema.json
```
"requires": ["local-reference", 
{"module": "dsdads", 
"submodule": "dsadasd", 
"element":"xxsax"} ]
```
"module" is optional, 
"conflicts" accepts same types,
"imports" are removed
> ASNIDE-243 Lib Module Schema updated - required/conflict fields merged with "imports"

- asn1acn.pro
- src/filesourcereader.cpp
- src/libraries/componentdirectorywatcher.cpp
- src/libraries/componentimporter.cpp
- src/libraries/componentimporter.h
- src/libraries/generalmetadataprocessor.cpp
- src/libraries/generalmetadataprocessor.h
- src/libraries/librarystorage.cpp
- src/libraries/librarystorage.h
- src/libraries/metadata/general.h
- src/libraries/wizard/selectsourcepage.cpp
- src/options-pages/librarieswidget.cpp
- it is not possible to import file to project more than once via wizard. It means that file will neither be copied nor added to project file. This is inconsistent with general Qt Creator behavior, but I came to conclusion, that it would be wrong in our case, as different library component might be using the same files, and the fact is hidden from the user. 
- the directory structure of imported file location will be recreated starting from the directory chosen in path chooser widget. For example, if user selects "Import Custom Library" from path ```/home``` , and after that in tree view marks for importing file  ```/home/asnide/workspace/asnide/asn1-pusc-lib/service-01/ErrorCodes.asn1``` , than the file will be copied into ```<Project …
```
> ASNIDE-230 Implemented copying files imported to project

- src/tests/projectcontenthandler_tests.cpp
- src/tests/projectcontenthandler_tests.h
The reason for the test failing was the same as previously, however this time I found the way to reproduce issue locally by executing tests in given order, so I believe it will not cause any surprises in future.
> Fixed OutlineIndexUpdaterTests occasionally failing

- asn1acn.pro
- src/asn1acn.cpp
- src/indenter.cpp
- src/tests/indenter_tests.cpp
- src/tests/indenter_tests.h
The idea to fix the issue is to assume, that if the line consist of more than curly bracket, than it is correctly indented. Rationale: In scenario, when code transits from:
```
1. firstLine
2. otherLine
```
to 
```
1. firstLine
2. otherLine {
```
The `otherLine` was always indented to `firstLine`. However, I believe there is no need to do so, as the lines would already be indented to the same level, because this is what happens after pressing `enter` at the end of line `firstLine`. This leads to conclusion, that if transition is from: 
```
1.     firstLine
2. otherLine
```
to 
```
1.     firstLine
2. otherLine {
```
there is no need to auto indent the `otherLine` as it must have been set this way deliberately by the user.
> ASNIDE-255 Made autoindention less forceful

- src/astxmlparser.cpp
- src/astxmlparser.h
- src/tests/astxmlparser_tests.cpp
- src/tests/astxmlparser_tests.h
George added "ParameterizedTypeInstance" attribute, so for now I'm just skipping parametrized instances. Maybe in future we'll get proper info about parametrized types instances...
> ASNIDE-222 Parametrized instances are ignored when searching of type references

- templates/wizards/projects/asn1acn/file.pro
Entries will now be indented equally, however entries added from .pro file template will be starting with `./` , while added through wizard will not be having this prefix. If really needed, this could be hacked, so both will miss the prefix. Other way might not be possible, as a result of internal ProjectExplorer implementation.
> ASNIDE-269 Increased indentation in qmake project file template

- src/tree-views/outlinewidget.cpp
- src/tree-views/treeviewwidget.cpp
- src/tree-views/treeviewwidget.h
This is what seems to provide best solution at the moment.
> ASNIDE-265 Fixed initial tree expansion in Outline view widget.

- src/libraries/filemodel.cpp
- src/libraries/metadatacheckstatehandler.cpp
- src/libraries/metadatacheckstatehandler.h
- src/libraries/metadatamodel.cpp
- src/libraries/metadatamodel.h
- src/libraries/tests/metadatacheckstatehandler_tests.cpp
Question asked in latest review reminded me of other place, which would benefit greatly from changing usage of `parent.child(i, j)`  to `model->index(i, j , parent)`. This was especially itchy, due to const_cast usage. Thanks to changes in this PR, casting constness was removed.
> Removed awkward rootIndex() method from MetadataModel

- templates/wizards/projects/asn1acn/generateFromAsn1.pri
- templates/wizards/projects/asn1acn/updateSourcesList.pri
generated/asn1crt.h -depends-on-> `*.asn` (building it calls asn1.exe)
generated/`*.c` -depends-on-> generated/asn1crt.h (empty build rule)
> ASNIDE-237 dependencies fixed in generated qmake project

- src/libraries/librarystorage.cpp
- src/libraries/wizard/relationslabelscontroller.cpp
- src/libraries/wizard/relationslabelscontroller.h
- src/libraries/wizard/selectcomponentspage.cpp
- src/libraries/wizard/selectcomponentspage.h
This prevents IDE from crashing when import component wizard is opened, and metadata files are edited externally.
> ASNIDE-238 Handled change in library when wizard window is opened

- src/buildicdstep.cpp
- templates/wizards/projects/asn1acn/generateFromAsn1.pri
- templates/wizards/projects/asn1acn/updateSourcesList.pri
The fix is included in last rc, and was tested on linux, clean linux and windows. 
I feel like I need to elaborate a little on this pull request. The goal of it is to fix qmake build in projects, which are in location containing spaces. The culprit breaking build in such situation was `eval` function, which after being called in following way: `eval($${file}_custom.target = $${file})` reported an error, if `$${file}` contained spaces. This happens because `$$file` is treated as two distinct arguments in such scenario, so the function call reports `Assignment needs exactly one word on the left hand side.`
Proposed solution is to strip spaces from the `$${file}`. My first idea was to used quotes (calling `shell_quote` on argument), but for some reason it does not work. I experimented with …
> Fix for qmake and icd build issue
